`ifndef LVC_AXI_DEFINES_SVH
`define LVC_AXI_DEFINES_SVH

// AXI4 Protocol Parameters
`define LVC_AXI_MAX_ADDR_WIDTH     64
`define LVC_AXI_MAX_DATA_WIDTH     1024
`define LVC_AXI_MAX_ID_WIDTH       16
`define LVC_AXI_MAX_BURST_LENGTH   256
`define LVC_AXI_MAX_STRB_WIDTH     (`LVC_AXI_MAX_DATA_WIDTH/8)

// Default values
`define LVC_AXI_DEFAULT_ADDR_WIDTH 32
`define LVC_AXI_DEFAULT_DATA_WIDTH 32
`define LVC_AXI_DEFAULT_ID_WIDTH   8
`define LVC_AXI_DEFAULT_STRB_WIDTH 4

`endif // LVC_AXI_DEFINES_SVH
